### ISSUE TITLE
rosmsg not working on Github Actions

### ISSUE THREAD

**Issue by aripod** [ros-tooling/ros-tooling.github.io#4]
Hi,

I am trying to run `rosmsg list > msgs.txt` following the examples and I get `rosmsg: not found` on that run. Here is the .yml:

```
name: ROS kinetic CI
on: [push]
jobs:
  # build:
  #   runs-on: ubuntu-18.04
  #   container: ros:melodic
  #   services:
  #     ros:
  #       image: ros
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #     - name: Save all ros msgs into a file
  #       run: rosmsg list > ros_msg_list.txt
  test_ros:
    name: "Test ROS package"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: # ROS 1 tests only run on Ubuntu
          #- kinetic
          - melodic
        include:
          # # Kinetic Kame (May 2016 - May 2021)
          # - docker_image: rostooling/setup-ros-docker:ubuntu-xenial-ros-kinetic-ros-base-latest
          #   ros_distribution: kinetic

          # Melodic Morenia (May 2018 - May 2023)
          - docker_image: rostooling/setup-ros-docker:ubuntu-bionic-ros-melodic-ros-base-latest
            ros_distribution: melodic
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "12.x"
      - run: rosmsg list > ros_msg_list.txt
``` 

I also tried the `build` job but the result was the same.
